### ISSUE TITLE
SIFT CLI - KDE Wallet Service

### ISSUE THREAD

**Issue by salty4n6** [teamdfir/sift#520]
Hi,
I installed SIFT on the SIFT OVA (sift was missing) and I'm doing a sift upgrade and I'm getting the following pop-up box.

![image](https://user-images.githubusercontent.com/81833785/115057274-771d4280-9ea9-11eb-8557-23b4acb4278b.png)

What package is doing this and what option should I pick?

Thanks,
Salty

**Comment by salty4n6** [comment]
I found reference to a similar issue and this seemed to resolve pip prompting for the KDE Wallet.

sudo python3 -m pip install --upgrade pip
sudo python3 -m pip install setuptools_rust
sudo -H pip3 uninstall keyring
sudo pip3 install --upgrade keyrings.alt

Salty

**Comment by ekristen** [comment]
Hey @salty4n6 -- what SIFT OVA are you using where SIFT is not installed, that doesn't seem correct?

The current community OVA on SANS website does not have the SIFT CLI installed but it is still 100% SIFT.

I've never seen KDE Wallet installed before, to my knowledge both 18.04 and 20.04 SIFT builds are gnome based not KDE, so not sure where KDE stuff is coming from unless you aren't actually using a SIFT OVA and instead using some other flavor of linux?

**Comment by ekristen** [comment]
Regardless, the KDE wallet is nothing being installed directly by SIFT, could be a dependency of something I suppose or installed by default? Could be wrong about KDE vs GNOME too.

**Comment by salty4n6** [comment]
Hi, The KDE wallet issue was happening on the latest OVA that doesn't have SIFT installed but I followed the instructions for installing SIFT so I can have an up to date system.  I have also done clean Ubuntu 18.04 and 20.04 installs and installed SIFT and both installs give the same KDE Wallet prompts.  The only packages I've installed before installing SIFT are build-essential, dkms, vim, and the virtualbox guest additions.  I also noticed that there seems to be an issue with the account creation?  I now have a user called {{ user }} on my systems. 

I'm going to do another clean install of Ubuntu 18.04, apply all the latest OS updates, and install the couple of packages I listed earlier and will post back.  I'll include the salt log file, too.

Salty

**Comment by salty4n6** [comment]
Hi,
I did a clean Ubuntu 18.04.5 install, updated everything, installed a couple of packages (vim, dkms, and build-essential),
 and VirtualBox guest additions.  I installed SIFT and the KDE Wallet prompt happened again.

I also have a new home directory called {{ user }}.

The install failed with the following:

>> Running: /usr/local/etc/foremost.conf
>> Running: sift-config-tools
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:542:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)


----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'



![Screenshot from 2021-04-17 15-00-53](https://user-images.githubusercontent.com/81833785/115125780-eda96580-9fb9-11eb-9f38-c226251d2443.png)

Thanks,
Salty
[saltstack.log](https://github.com/teamdfir/sift/files/6329962/saltstack.log)

**Comment by ekristen** [comment]
I will take a look, we have primarily started to move on to 20.04, might be worth a try too

**Comment by salty4n6** [comment]
I'll give 20.04 a rip and let you know.

**Comment by salty4n6** [comment]
20.04 has the same KDE Wallet pop-up and the {{ user }} issue.  From looking at the salt.log, it looks like the errors are related to the changes to the sansforensics user account.  The KDE prompt is still strange but I'll run the SIFT install again to see if it comes back and if it does then I'll run the other commands I found earlier then run SIFT install again to see if the prompt comes back.

Salty

[saltstack.log](https://github.com/teamdfir/sift/files/6331352/saltstack.log)

**Comment by salty4n6** [comment]
Good news is the system knows that SIFT is installed 

![image](https://user-images.githubusercontent.com/81833785/115147563-1463ac80-a04b-11eb-8fb9-962adbe75fc9.png)

running sudo sift update now

**Comment by salty4n6** [comment]
sudo sift update prompts for the KDE Wallet then I ran

sudo python3 -m pip install --upgrade pip
sudo python3 -m pip install setuptools_rust
sudo -H pip3 uninstall keyring
sudo pip3 install --upgrade keyrings.alt

I ran sudo sift update and the KDE Wallet prompts are gone.  Not sure what all is going on.

Salty

I attached the salt log for the last run with the upgrade to keyrings.alt
[sift-keyrings-upgrade.log](https://github.com/teamdfir/sift/files/6331380/sift-keyrings-upgrade.log)

**Comment by ekristen** [comment]
I haven't seen this happen through normal use, but since you are upgrading pip, perhaps it's related to that. I'll check with a few others as well.

**Comment by esentner** [comment]
I saw the same popup when I installed on a fresh 18.04 box yesterday. The install error'd out from lack of space, so I had to add more space to root and tried again, and the popup didn't come back but it still gave an error and left a {{user}} folder in /home.  I thought something broke due to the space issue and since there's no way to uninstall sift, I've rebuilt the box with 20.04 and and trying the install again now.

One other thing I noticed is that the verification of the asc file doesn't work using gpg, as the file is created in openpgp instead.

**Comment by ekristen** [comment]
I'll take ac closer look tonight/tomorrow, some recent changes were made with the user, but I think we fixed one bug but might not have pushed the change.

Regard PGP, it shouldn't matter PGP is PGP, but I'll verify and see what's causing a problem.

**Comment by esentner** [comment]
```
~/Downloads$ gpg --verify sift-cli-linux.sha256.asc
gpg: verify signatures failed: Unexpected error
```

```
~/Downloads$ gpg -v -d sift-cli-linux.sha256.asc 
gpg: armor header: Version: OpenPGP.js v4.10.1
gpg: armor header: Comment: https://openpgpjs.org
gpg: public key is A2156B0CEAE26425
gpg: using subkey A2156B0CEAE26425 instead of primary key 15B9AD7122598A94
gpg: encrypted with 4096-bit ELG key, ID A2156B0CEAE26425, created 2013-12-07
      "SANS Investigative Forensic Toolkit <sift@computer-forensics.sans.org>"
gpg: decryption failed: No secret key

```

**Comment by esentner** [comment]
Tried older release of sift-cli (1.9.2) and it still errors out.
```
>> Running: /usr/local/etc/foremost.conf
>> Running: sift-config-tools
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:547:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)


----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'

**~/Downloads$ ls /home
 sentner  '{{ user }}'**
```

```
/var$ tail /var/cache/sift/cli/v2021.4.2/saltstack.log
  user_|-sift-user-sentner_|-sentner_|-present:
    __id__: sift-user-sentner
    __run_num__: 561
    __sls__: sift.config.user.user
    changes: {}
    comment: 'These values could not be changed: {''home'': ''/home/{{ user }}''}'
    duration: 14.622
    name: sentner
    result: false
    start_time: '03:48:14.323389'
```

**Comment by ekristen** [comment]
I believe this was an accidental bug introduced in 2021.4.2, but not seeing it in 2021.4.3. Please run an upgrade or fresh install and let me know. I'm doing a full run through as we speak.

**Comment by salty4n6** [comment]
Hi Erik,
I did a clean install of Ubuntu 20.04 and installed with the latest version 2021.4.3 and I had the same results ( KDE Wallet and {{ user }}). I ran a sift update afterwards and I'm still getting errors.  I'm attaching the log for the update.  I forgot to grab the log for the clean install.
Thanks,
Salty
[saltstack.log](https://github.com/teamdfir/sift/files/6347506/saltstack.log)

**Comment by salty4n6** [comment]
Hi Erik,
I did a clean install of Ubuntu 20.04 and installed with the latest version 2021.4.3 and I had the same results ( KDE Wallet and {{ user }}). I ran a sift update afterwards and I'm still getting errors.  I'm attaching the log for the update.  I forgot to grab the log for the clean install.
Thanks,
Salty
[saltstack.log](https://github.com/teamdfir/sift/files/6347506/saltstack.log)

**Comment by ekristen** [comment]
I’m running another build now, so far haven’t reproduced it.

**Comment by ekristen** [comment]
Ok I duplicated this as well. Looks like they are entirely unrelated.

**Comment by salty4n6** [comment]
Good timing.  I was just about to post my update from another machine going from 2021.4.2 to 2021.4.3.

Thank you for looking into these issues.

**Comment by ekristen** [comment]
I have a fix for `{{ user }}` -- we'll see if they are actually linked together. I spun up an older OVA that doesn't have any of these issues. Looking at the differences.

**Comment by ekristen** [comment]
It's the latest version of pip that is doing the KDE wallet stuff. Pip wants to create a wallet for some reason :/

**Comment by ekristen** [comment]
Apparently this is a known issue that is being worked on in a number of different ways.

**Comment by salty4n6** [comment]
Just upgraded via 2021.4.4 - all good with the {{ user }}.  Thanks Erik.

**Comment by ekristen** [comment]
Glad it's working.
